name: CI

on: push

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
      - name: Run tests
        run: |
          for day in */; do
              python "$day"
          done
